export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    LOGOUT_ALL: '/auth/logout-all',
    ME: '/auth/me',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    CHANGE_EMAIL: '/auth/change-email',
    UPDATE_PROFILE: '/auth/update-profile',
    TWO_FACTOR_SETUP: '/auth/2fa/setup',
    TWO_FACTOR_CONFIRM: '/auth/2fa/confirm',
    TWO_FACTOR_AUTHENTICATE: '/auth/2fa/authenticate',
    TWO_FACTOR_DISABLE: '/auth/2fa/disable',
  },
  DASHBOARD_STATS: '/dashboard/stats',
  USERS: '/users',
  ROLES: '/roles',
  TODOS: '/todos',
  AUDITS: '/audits',
  PERMISSIONS: '/permissions',
} as const;
